apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: __NAMESPACE__
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-coffee-shop:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
  - name: keyPrefix
    value: __DAPR_APP_ID__
